version: '3'
services:
   prisma:
      image: prismagraphql/prisma:1.34
      restart: always
      ports:
      - "4466:4466"
      environment:
         PRISMA_CONFIG: |
            port: 4466
            # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
            # managementApiSecret: my-secret
            databases:
               default:
                  connector: postgres
                  host: ec2-54-246-90-10.eu-west-1.compute.amazonaws.com
                  database: d33tifdjut1ud9
                  user: kgvdpltiagzreg
                  password: 4319597de11ca66cce542bdf9fa90f295d6e11258c5285713a0279e2f7de5970
                  ssl: true
                  rawAccess: true
                  port: '5432'
                  migrations: true